### ISSUE TITLE
Duplicate (and misleading) testing of different python versions in GitHub workflows + tox

### ISSUE THREAD

**Issue by andhus** [andhus/scantree#12]
In fact, I think we should pull out tox and rely on GitHub workflows for the "matrix" of different python versions (which is primarily what it is used for). Right now (after the merge of this PR) we test multiple python version multiple times (because tox matrix is run for each workflow python version) which is unnecessary and misleading if there is a failure, see: https://github.com/andhus/scantree/actions/runs/7415433113/job/20178552710#step:6:32 and compare with job name :/

_Originally posted by @andhus in https://github.com/andhus/scantree/pull/11#discussion_r1442308771_

**Comment by iurisilvio** [comment]
Running all Python versions local with tox is good.

In my projects, I use [tox-gh-actions](https://github.com/ymyzk/tox-gh-actions) to run the matrix and the action filter only matching tox environments. Output example: https://github.com/businho/django-migrations-ci/actions/runs/7141753527/job/19449603078#step:7:16147
